# Compilador e flags
GO = go
BINARY = app
SRC_DIR = .

# Compila o projeto gerando um executável
all:
	$(GO) build -o $(BINARY) $(SRC_DIR)

# Roda o executável gerado
run:
	./$(BINARY)

# Remove o executável gerado
clean:
	rm -f $(BINARY)